/* EmbeddedImporter C bridge module (Python 3.13) */

#include "Python.h"

#include <stdint.h>
#include <zstd.h>

#ifdef MS_WINDOWS
#include <windows.h>
#endif

/* External references to embedded data (generated by create_embeddedimporter_data.py) */
extern char embeddedimporter_filename[];
extern const size_t embeddedimporter_raw_data_size;
extern const unsigned char embeddedimporter_raw_data_compressed[];
extern const size_t embeddedimporter_raw_data_compressed_size;
extern const size_t embeddedimporter_data_offset[];
/* Same as create_embeddedimporter_gperf_keyfile.txt */
struct file_offset {
    const char *filename;
    size_t offset;
    size_t size;
};
struct file_offset *
embeddedimporter_find_entry (register const char *str, register unsigned int len);

#ifdef Py_BUILD_RESOURCE_EMBEDDED_MODULE
#define USER_SOURCE_ID 200
#endif

static int embedded_data_initialized = 0;
static unsigned char *embedded_raw_data = NULL;

#ifdef Py_BUILD_RESOURCE_EMBEDDED_MODULE
static int embedded_resource_initialized = 0;
static unsigned char *embedded_raw_data_resource = NULL;
#endif
static size_t embedded_raw_data_resource_size = 0;
static PyObject *embedded_index_resource = NULL;

#ifdef Py_BUILD_RESOURCE_EMBEDDED_MODULE
#error Not Implemented.
static int ensure_resource_data(void);
#endif

static PyObject *
load_helper_module(void)
{
    const char filename_str[] = "embeddedimport_helper.py";
    struct file_offset *entry = embeddedimporter_find_entry(filename_str, sizeof(filename_str) - 1);
    if (entry == NULL) {
        return NULL;
    }

    PyObject *name = PyUnicode_FromString("embeddedimport_helper");
    if (name == NULL) {
        return NULL;
    }

    PyObject *filename = PyUnicode_FromString(filename_str);
    if (filename == NULL) {
        Py_DECREF(name);
        return NULL;
    }

    unsigned char *data = embedded_raw_data;
    const char *buffer = (const char *)data + entry->offset;
    PyObject *code = Py_CompileStringObject(buffer, filename, Py_file_input, NULL, -1);
    if (code == NULL) {
        Py_DECREF(name);
        Py_DECREF(filename);
        return NULL;
    }

    PyObject *module = PyImport_ExecCodeModuleObject(name, code, name, NULL);
    Py_DECREF(code);
    Py_DECREF(filename);
    Py_DECREF(name);
    return module;
}

static int
ensure_embedded_data(void)
{
    if (embedded_data_initialized) {
        return 0;
    }

    embedded_raw_data = (unsigned char *)PyMem_Malloc(embeddedimporter_raw_data_size);
    if (embedded_raw_data == NULL) {
        PyErr_NoMemory();
        return -1;
    }

    size_t result_len = ZSTD_decompress(embedded_raw_data,
                                        embeddedimporter_raw_data_size,
                                        embeddedimporter_raw_data_compressed,
                                        embeddedimporter_raw_data_compressed_size);
    if (ZSTD_isError(result_len) || result_len != embeddedimporter_raw_data_size) {
        PyMem_Free(embedded_raw_data);
        embedded_raw_data = NULL;
        PyErr_SetString(PyExc_ImportError, "zstd decompress failed");
        return -1;
    }

    embedded_data_initialized = 1;
    return 0;
}

#ifdef Py_BUILD_RESOURCE_EMBEDDED_MODULE
static int
ensure_resource_data(void)
{
    if (embedded_resource_initialized) {
        return 0;
    }

    HRSRC hResource = FindResource(NULL, MAKEINTRESOURCE(USER_SOURCE_ID), RT_RCDATA);
    if (hResource == NULL) {
        embedded_index_resource = PyDict_New();
        if (embedded_index_resource == NULL) {
            return -1;
        }
        embedded_resource_initialized = 1;
        return 0;
    }

    HGLOBAL hLoadedResource = LoadResource(NULL, hResource);
    if (hLoadedResource == NULL) {
        PyErr_SetString(PyExc_ImportError, "Failed to load resource");
        return -1;
    }

    LPVOID pLockedResource = LockResource(hLoadedResource);
    if (pLockedResource == NULL) {
        PyErr_SetString(PyExc_ImportError, "Failed to lock resource");
        return -1;
    }

    DWORD dwResourceSize = SizeofResource(NULL, hResource);
    unsigned char *resource_data = (unsigned char *)pLockedResource;

    if (dwResourceSize < 12) {
        PyErr_SetString(PyExc_ImportError, "Resource data too small");
        return -1;
    }

    uint32_t compressed_size, uncompressed_size, file_count;
    memcpy(&compressed_size, resource_data, 4);
    memcpy(&uncompressed_size, resource_data + 4, 4);
    memcpy(&file_count, resource_data + 8, 4);

    if (dwResourceSize < 12 + file_count * 4 + compressed_size) {
        PyErr_SetString(PyExc_ImportError, "Invalid resource data");
        return -1;
    }

    uint32_t *file_offsets = (uint32_t *)(resource_data + 12);
    unsigned char *compressed_file_data = resource_data + 12 + file_count * 4;
    char *file_names = (char *)(compressed_file_data + compressed_size);

    if (uncompress_data(compressed_file_data, compressed_size,
                        &embedded_raw_data_resource,
                        uncompressed_size) < 0) {
        return -1;
    }

    embedded_raw_data_resource_size = uncompressed_size;

    PyObject *toc = PyDict_New();
    if (toc == NULL) {
        return -1;
    }

    for (uint32_t i = 0; i < file_count; i++) {
        const char *filename = file_names;
        size_t offset = file_offsets[i];
        size_t size;
        PyObject *key, *value;

        while (*file_names != '\0') {
            file_names++;
        }
        file_names++;

        if (i + 1 < file_count) {
            size = file_offsets[i + 1] - offset;
        } else {
            size = uncompressed_size - offset;
        }

        if (size > 0 && embedded_raw_data_resource[offset + size - 1] == '\0') {
            size -= 1;
        }

        key = PyUnicode_FromString(filename);
        if (key == NULL) {
            Py_DECREF(toc);
            return -1;
        }
        value = Py_BuildValue("(nn)", (Py_ssize_t)offset, (Py_ssize_t)size);
        if (value == NULL) {
            Py_DECREF(key);
            Py_DECREF(toc);
            return -1;
        }

        if (PyDict_SetItem(toc, key, value) < 0) {
            Py_DECREF(key);
            Py_DECREF(value);
            Py_DECREF(toc);
            return -1;
        }

        Py_DECREF(key);
        Py_DECREF(value);
    }

    embedded_index_resource = toc;
    embedded_resource_initialized = 1;
    return 0;
}
#endif

static PyObject *
embeddedimport_find_entry(PyObject *self, PyObject *args)
{
    const char *filename;

    if (!PyArg_ParseTuple(args, "s", &filename)) {
        return NULL;
    }

    struct file_offset *entry = embeddedimporter_find_entry(filename, (unsigned int)strlen(filename));
    if (entry == NULL) {
        Py_RETURN_NONE;
    }

    return Py_BuildValue("(nn)", (Py_ssize_t)entry->offset, (Py_ssize_t)entry->size);
}

static PyObject *
embeddedimport_find_entry_in_resource(PyObject *self, PyObject *args)
{
    const char *filename;

    if (!PyArg_ParseTuple(args, "s", &filename)) {
        return NULL;
    }

    Py_RETURN_NONE;
}

static PyObject *
embeddedimport_get_data(PyObject *self, PyObject *args, PyObject *kwargs)
{
    Py_ssize_t offset, size;
    int use_resource = 0;
    static char *keywords[] = {"offset", "size", "use_resource", NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, "nn|p", keywords,
                                     &offset, &size, &use_resource)) {
        return NULL;
    }

    if (offset < 0 || size < 0) {
        PyErr_SetString(PyExc_ValueError, "offset and size must be non-negative");
        return NULL;
    }

    unsigned char *data = NULL;
    size_t data_size = 0;

    if (use_resource) {
#ifdef Py_BUILD_RESOURCE_EMBEDDED_MODULE
        if (ensure_resource_data() < 0) {
            return NULL;
        }
        data = embedded_raw_data_resource;
        data_size = embedded_raw_data_resource_size;
#else
        PyErr_SetString(PyExc_ValueError, "resource data not available");
        return NULL;
#endif
    } else {
        if (ensure_embedded_data() < 0) {
            return NULL;
        }
        data = embedded_raw_data;
        data_size = embeddedimporter_raw_data_size;
    }

    if (data == NULL) {
        PyErr_SetString(PyExc_ValueError, "embedded data not initialized");
        return NULL;
    }

    if ((size_t)offset + (size_t)size > data_size) {
        PyErr_SetString(PyExc_ValueError, "offset/size out of range");
        return NULL;
    }

    return PyBytes_FromStringAndSize((const char *)data + offset, size);
}

static PyMethodDef embeddedimport_methods[] = {
    {"_find_entry", embeddedimport_find_entry, METH_VARARGS,
     "Return (offset, size) for embedded data."},
    {"_find_entry_in_resource", embeddedimport_find_entry_in_resource, METH_VARARGS,
     "Return (offset, size) for embedded data."},
    {"_get_data", (PyCFunction)embeddedimport_get_data, METH_VARARGS | METH_KEYWORDS,
     "_get_data(offset, size, use_resource=False) -> bytes"},
    {NULL, NULL}
};

static int
embeddedimport_exec(PyObject *m)
{
    /* Load Python helper module from embedded data and re-export class */
    if (ensure_embedded_data() < 0) {
        return -1;
    }

    PyObject *helper = load_helper_module();
    if (helper == NULL) {
        return -1;
    }

    PyObject *cls = PyObject_GetAttrString(helper, "EmbeddedImporter");
    Py_DECREF(helper);
    if (cls == NULL) {
        return -1;
    }

    if (PyModule_AddObject(m, "embeddedimporter", cls) < 0) {
        Py_DECREF(cls);
        return -1;
    }

    return 0;
}

static PyModuleDef_Slot embeddedimport_slots[] = {
    {Py_mod_multiple_interpreters, Py_MOD_PER_INTERPRETER_GIL_SUPPORTED},
    {Py_mod_exec, embeddedimport_exec},
    {0, NULL}
};

static struct PyModuleDef embeddedimportmodule = {
    PyModuleDef_HEAD_INIT,
    "embeddedimport",
    "Embedded importer helper module.",
    0,
    embeddedimport_methods,
    embeddedimport_slots,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC
PyInit_embeddedimport(void)
{
    return PyModuleDef_Init(&embeddedimportmodule);
}

