/* EmbeddedImporter C bridge module (Python 3.13) */

#include "Python.h"

#include <stdint.h>
#include <zstd.h>

#ifdef MS_WINDOWS
#include <windows.h>
#endif

/* External references to embedded data (generated by create_embeddedimporter_data.py) */
extern char embeddedimporter_filename[];
extern const size_t embeddedimporter_raw_data_size;
extern const unsigned char embeddedimporter_raw_data_compressed[];
extern const size_t embeddedimporter_raw_data_compressed_size;
extern const size_t embeddedimporter_data_offset[];

#ifdef Py_BUILD_RESOURCE_EMBEDDED_MODULE
#define USER_SOURCE_ID 200
#endif

static int embedded_data_initialized = 0;
static unsigned char *embedded_raw_data = NULL;
static PyObject *embedded_index = NULL;

#ifdef Py_BUILD_RESOURCE_EMBEDDED_MODULE
static int embedded_resource_initialized = 0;
static unsigned char *embedded_raw_data_resource = NULL;
#endif
static size_t embedded_raw_data_resource_size = 0;
static PyObject *embedded_index_resource = NULL;

static PyObject *EmbeddedImportError = NULL;

static int build_embedded_index(void);
#ifdef Py_BUILD_RESOURCE_EMBEDDED_MODULE
static int ensure_resource_data(void);
#endif

static PyObject *
load_helper_module(void)
{
    if (build_embedded_index() < 0) {
        return NULL;
    }

#ifdef Py_BUILD_RESOURCE_EMBEDDED_MODULE
    if (ensure_resource_data() < 0) {
        return NULL;
    }
#endif

    PyObject *entry = PyDict_GetItemString(embedded_index, "embeddedimport_helper.py");
#ifdef Py_BUILD_RESOURCE_EMBEDDED_MODULE
    if (entry == NULL && embedded_index_resource != NULL && embedded_index_resource != Py_None) {
        entry = PyDict_GetItemString(embedded_index_resource, "embeddedimport_helper.py");
    }
#endif
    if (entry == NULL) {
        PyErr_Clear();
        return PyImport_ImportModule("embeddedimport_helper");
    }

    Py_ssize_t offset, size;
    if (!PyArg_ParseTuple(entry, "nn", &offset, &size)) {
        return NULL;
    }

    unsigned char *data = embedded_raw_data;
#ifdef Py_BUILD_RESOURCE_EMBEDDED_MODULE
    if (embedded_index_resource != NULL && embedded_index_resource != Py_None) {
        if (PyDict_GetItemString(embedded_index_resource, "embeddedimport_helper.py") == entry) {
            data = embedded_raw_data_resource;
        }
    }
#endif

    PyObject *name = PyUnicode_FromString("embeddedimport_helper");
    if (name == NULL) {
        return NULL;
    }

    PyObject *filename = PyUnicode_FromString("embeddedimport_helper.py");
    if (filename == NULL) {
        Py_DECREF(name);
        return NULL;
    }

    const char *buffer = (const char *)data + offset;
    PyObject *code = Py_CompileStringObject(buffer, filename, Py_file_input, NULL, -1);
    if (code == NULL) {
        Py_DECREF(name);
        Py_DECREF(filename);
        return NULL;
    }

    PyObject *module = PyImport_ExecCodeModuleObject(name, code, name, NULL);
    Py_DECREF(code);
    Py_DECREF(filename);
    Py_DECREF(name);
    return module;
}

static size_t
count_filenames(const char *p)
{
    size_t count = 0;
    while (*p != '\0') {
        while (*p != '\0') {
            p++;
        }
        p++;
        count++;
    }
    return count;
}

static int
ensure_embedded_data(void)
{
    if (embedded_data_initialized) {
        return 0;
    }

    embedded_raw_data = (unsigned char *)PyMem_Malloc(embeddedimporter_raw_data_size);
    if (embedded_raw_data == NULL) {
        PyErr_NoMemory();
        return -1;
    }

    size_t result_len = ZSTD_decompress(embedded_raw_data,
                                        embeddedimporter_raw_data_size,
                                        embeddedimporter_raw_data_compressed,
                                        embeddedimporter_raw_data_compressed_size);
    if (ZSTD_isError(result_len) || result_len != embeddedimporter_raw_data_size) {
        PyMem_Free(embedded_raw_data);
        embedded_raw_data = NULL;
        PyErr_SetString(EmbeddedImportError, "zstd decompress failed");
        return -1;
    }

    embedded_data_initialized = 1;
    return 0;
}

static int
build_embedded_index(void)
{
    if (embedded_index != NULL) {
        return 0;
    }

    if (ensure_embedded_data() < 0) {
        return -1;
    }

    PyObject *toc = PyDict_New();
    if (toc == NULL) {
        return -1;
    }

    const char *p = embeddedimporter_filename;
    size_t file_count = count_filenames(p);
    size_t i = 0;

    while (*p != '\0') {
        const char *filename = p;
        size_t offset, size;
        PyObject *key, *value;

        while (*p != '\0') {
            p++;
        }
        p++; /* skip NULL */

        offset = embeddedimporter_data_offset[i];
        if (i + 1 < file_count) {
            size = embeddedimporter_data_offset[i + 1] - offset;
        } else {
            size = embeddedimporter_raw_data_size - offset;
        }
        i++;

        if (size > 0 && embedded_raw_data[offset + size - 1] == '\0') {
            size -= 1;
        }

        key = PyUnicode_FromString(filename);
        if (key == NULL) {
            Py_DECREF(toc);
            return -1;
        }
        value = Py_BuildValue("(nn)", (Py_ssize_t)offset, (Py_ssize_t)size);
        if (value == NULL) {
            Py_DECREF(key);
            Py_DECREF(toc);
            return -1;
        }

        if (PyDict_SetItem(toc, key, value) < 0) {
            Py_DECREF(key);
            Py_DECREF(value);
            Py_DECREF(toc);
            return -1;
        }

        Py_DECREF(key);
        Py_DECREF(value);
    }

    embedded_index = toc;
    return 0;
}

#ifdef Py_BUILD_RESOURCE_EMBEDDED_MODULE
static int
ensure_resource_data(void)
{
    if (embedded_resource_initialized) {
        return 0;
    }

    HRSRC hResource = FindResource(NULL, MAKEINTRESOURCE(USER_SOURCE_ID), RT_RCDATA);
    if (hResource == NULL) {
        embedded_index_resource = PyDict_New();
        if (embedded_index_resource == NULL) {
            return -1;
        }
        embedded_resource_initialized = 1;
        return 0;
    }

    HGLOBAL hLoadedResource = LoadResource(NULL, hResource);
    if (hLoadedResource == NULL) {
        PyErr_SetString(EmbeddedImportError, "Failed to load resource");
        return -1;
    }

    LPVOID pLockedResource = LockResource(hLoadedResource);
    if (pLockedResource == NULL) {
        PyErr_SetString(EmbeddedImportError, "Failed to lock resource");
        return -1;
    }

    DWORD dwResourceSize = SizeofResource(NULL, hResource);
    unsigned char *resource_data = (unsigned char *)pLockedResource;

    if (dwResourceSize < 12) {
        PyErr_SetString(EmbeddedImportError, "Resource data too small");
        return -1;
    }

    uint32_t compressed_size, uncompressed_size, file_count;
    memcpy(&compressed_size, resource_data, 4);
    memcpy(&uncompressed_size, resource_data + 4, 4);
    memcpy(&file_count, resource_data + 8, 4);

    if (dwResourceSize < 12 + file_count * 4 + compressed_size) {
        PyErr_SetString(EmbeddedImportError, "Invalid resource data");
        return -1;
    }

    uint32_t *file_offsets = (uint32_t *)(resource_data + 12);
    unsigned char *compressed_file_data = resource_data + 12 + file_count * 4;
    char *file_names = (char *)(compressed_file_data + compressed_size);

    if (uncompress_data(compressed_file_data, compressed_size,
                        &embedded_raw_data_resource,
                        uncompressed_size) < 0) {
        return -1;
    }

    embedded_raw_data_resource_size = uncompressed_size;

    PyObject *toc = PyDict_New();
    if (toc == NULL) {
        return -1;
    }

    for (uint32_t i = 0; i < file_count; i++) {
        const char *filename = file_names;
        size_t offset = file_offsets[i];
        size_t size;
        PyObject *key, *value;

        while (*file_names != '\0') {
            file_names++;
        }
        file_names++;

        if (i + 1 < file_count) {
            size = file_offsets[i + 1] - offset;
        } else {
            size = uncompressed_size - offset;
        }

        if (size > 0 && embedded_raw_data_resource[offset + size - 1] == '\0') {
            size -= 1;
        }

        key = PyUnicode_FromString(filename);
        if (key == NULL) {
            Py_DECREF(toc);
            return -1;
        }
        value = Py_BuildValue("(nn)", (Py_ssize_t)offset, (Py_ssize_t)size);
        if (value == NULL) {
            Py_DECREF(key);
            Py_DECREF(toc);
            return -1;
        }

        if (PyDict_SetItem(toc, key, value) < 0) {
            Py_DECREF(key);
            Py_DECREF(value);
            Py_DECREF(toc);
            return -1;
        }

        Py_DECREF(key);
        Py_DECREF(value);
    }

    embedded_index_resource = toc;
    embedded_resource_initialized = 1;
    return 0;
}
#endif

static PyObject *
embeddedimport_get_index(PyObject *self, PyObject *args)
{
    if (build_embedded_index() < 0) {
        return NULL;
    }

#ifdef Py_BUILD_RESOURCE_EMBEDDED_MODULE
    if (ensure_resource_data() < 0) {
        return NULL;
    }
#else
    if (embedded_index_resource == NULL) {
        embedded_index_resource = Py_None;
        Py_INCREF(Py_None);
    }
#endif

    Py_INCREF(embedded_index);
    Py_INCREF(embedded_index_resource);
    return PyTuple_Pack(2, embedded_index, embedded_index_resource);
}

static PyObject *
embeddedimport_get_data(PyObject *self, PyObject *args, PyObject *kwargs)
{
    Py_ssize_t offset, size;
    int use_resource = 0;
    static char *keywords[] = {"offset", "size", "use_resource", NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, "nn|p", keywords,
                                     &offset, &size, &use_resource)) {
        return NULL;
    }

    if (offset < 0 || size < 0) {
        PyErr_SetString(PyExc_ValueError, "offset and size must be non-negative");
        return NULL;
    }

    unsigned char *data = NULL;
    size_t data_size = 0;

    if (use_resource) {
#ifdef Py_BUILD_RESOURCE_EMBEDDED_MODULE
        if (ensure_resource_data() < 0) {
            return NULL;
        }
        data = embedded_raw_data_resource;
        data_size = embedded_raw_data_resource_size;
#else
        PyErr_SetString(PyExc_ValueError, "resource data not available");
        return NULL;
#endif
    } else {
        if (ensure_embedded_data() < 0) {
            return NULL;
        }
        data = embedded_raw_data;
        data_size = embeddedimporter_raw_data_size;
    }

    if (data == NULL) {
        PyErr_SetString(PyExc_ValueError, "embedded data not initialized");
        return NULL;
    }

    if ((size_t)offset + (size_t)size > data_size) {
        PyErr_SetString(PyExc_ValueError, "offset/size out of range");
        return NULL;
    }

    return PyBytes_FromStringAndSize((const char *)data + offset, size);
}

static PyMethodDef embeddedimport_methods[] = {
    {"_get_index", embeddedimport_get_index, METH_NOARGS,
     "Return (index, resource_index) for embedded data."},
    {"_get_data", (PyCFunction)embeddedimport_get_data, METH_VARARGS | METH_KEYWORDS,
     "_get_data(offset, size, use_resource=False) -> bytes"},
    {NULL, NULL}
};

static struct PyModuleDef embeddedimportmodule = {
    PyModuleDef_HEAD_INIT,
    "embeddedimport",
    "Embedded importer helper module.",
    -1,
    embeddedimport_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC
PyInit_embeddedimport(void)
{
    PyObject *m = PyModule_Create(&embeddedimportmodule);
    if (m == NULL) {
        return NULL;
    }

    EmbeddedImportError = PyErr_NewExceptionWithDoc(
        "embeddedimport.EmbeddedImportError",
        "Exception raised by embeddedimport.",
        PyExc_ImportError,
        NULL);
    if (EmbeddedImportError == NULL) {
        Py_DECREF(m);
        return NULL;
    }
    if (PyModule_AddObject(m, "EmbeddedImportError", EmbeddedImportError) < 0) {
        Py_DECREF(EmbeddedImportError);
        Py_DECREF(m);
        return NULL;
    }

    /* Load Python helper module from embedded data and re-export class */
    PyObject *helper = load_helper_module();
    if (helper == NULL) {
        Py_DECREF(m);
        return NULL;
    }

    PyObject *cls = PyObject_GetAttrString(helper, "EmbeddedImporter");
    Py_DECREF(helper);
    if (cls == NULL) {
        Py_DECREF(m);
        return NULL;
    }

    if (PyModule_AddObject(m, "embeddedimporter", cls) < 0) {
        Py_DECREF(cls);
        Py_DECREF(m);
        return NULL;
    }

    return m;
}
