name: Build

on:
  workflow_dispatch:
  push:
    branches:
    - 'single_binary_python'
    - 'sample'

permissions:
  contents: read

env:
  FORCE_COLOR: 1

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: "Disable git autoCRLF"
      run: git config --global core.autoCRLF false
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Get externals
      run: cmd /c SingleBinaryBuild\get_externals.bat --tkinter-src --openssl-src --libffi-src
    - name: Build libffi
      run: |
        set LIBFFI_SOURCE=%CD%\externals\libffi-3.4.4
        set "VCVARSALL=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat"
        call SingleBinaryBuild\prepare_libffi.bat -x64 --install-cygwin
      shell: cmd
    - name: Build openssl
      run: cmd /c SingleBinaryBuild\prepare_ssl.bat
    - name: Build tcl/tk
      run: cmd /c SingleBinaryBuild\prepare_tcltk.bat
    - name: Generate embedded resources.
      run: |
        $ErrorActionPreference = 'Stop'
        .\SingleBinaryBuild\external_tools\sbpython.exe SingleBinaryBuild/create_embeddedimporter_data.py
        .\SingleBinaryBuild\external_tools\sbpython.exe SingleBinaryBuild/create_tcl_embeddedfilesystem_data.py externals/tcltk-8.6.15.0/amd64/lib Modules/_tkinter_tclEmbeddedFilesystemData.c
      shell: pwsh
    - name: Build CPython
      run: cmd /c SingleBinaryBuild.bat
    - name: Prepare artifact
      run: |
        md artifact
        copy SingleBinaryBuild\amd64\python.exe artifact\sbpython.exe
        copy SingleBinaryBuild\amd64\pythonw.exe artifact\sbpythonw.exe
      shell: cmd
    - uses: actions/upload-artifact@v4
      with:
        name: python
        path: artifact/*.exe
    - name: Display build info
      run: ".\\python.bat -m test.pythoninfo"
    - name: Test
      # To avoid reload(_queue) bug, test_interpreters should be run separately.
      run: |
        $ErrorActionPreference = 'Stop'
        copy SingleBinaryBuild\amd64\python.exe .\sbpython.exe
        .\sbpython.exe -m test.regrtest --use=largefile,network,decimal,cpu,subprocess,urlfetch,gui -x test_capi test_cext test_cppext test_dtrace test_ensurepip test_idle test_interpreters test_pydoc test_venv
      shell: pwsh
    - name: Test test_interpreters
      run: |
        $ErrorActionPreference = 'Stop'
        .\sbpython.exe -m test.regrtest test_interpreters
      shell: pwsh
